[package]
name = "Tracer CLI"
version = "0.1.0"
authors = ["Pascal Hertleif <developers@tacer.bio>"]
edition = "2024"

# Make tests work with the name used in the tutorial
[[bin]]
name = "tracer-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
anyhow = "1.0.81"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
assert_fs = "1.1.1"
