name: Rust CI

on:
  push:
    branches:
      - master # Trigger on pushes to master
      - develop # Trigger on pushes to develop
  pull_request:
    branches:
      - master # Trigger on pull requests to master
      - develop # Trigger on pull requests to develop

env:
  CARGO_TERM_COLOR: always # Ensures colored output in GitHub Actions logs

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest # Specifies the runner

    steps:
      - uses: actions/checkout@v4.1.4

      - run: rustup toolchain install stable --profile minimal

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Build
        run: cargo build --verbose # Compiles the package and all of its dependencies

      - name: Run tests
        run: cargo test --verbose # Runs tests

      - name: Check Formatting
        run: cargo fmt -- --check # Checks formatting of the code base to ensure it's in the correct style

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings # Runs Clippy to catch common mistakes and improve your Rust code
