name: Deploy to Cloudflare R2

on:
  push:
    branches:
      - master
      - dev

jobs:
  upload-to-r2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload script to Cloudflare R2
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_R2_BUCKET_NAME: ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }}
        run: |
          # Install required packages
          sudo apt-get update
          sudo apt-get install -y curl jq

          # Define variables
          FILE_PATH="install-tracer.sh"
          BUCKET_NAME="$CLOUDFLARE_R2_BUCKET_NAME"
          ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID"
          API_TOKEN="$CLOUDFLARE_API_TOKEN"

          # Get R2 endpoint
          ENDPOINT=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/r2/storage" \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" | jq -r '.result[0].endpoint')

          # Upload the file to R2
          curl -X PUT "$ENDPOINT/$BUCKET_NAME/$FILE_PATH" \
            -H "Authorization: Bearer $API_TOKEN" \
            --upload-file $FILE_PATH
