name: Automatic Version Bump and Tagging

on:
  push:
    branches:
      - master # or main, depending on your default branch name

jobs:
  bump_version_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for tags and history

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run Tests
        run: cargo test --verbose

      - name: Determine Version Bump and Update Cargo.toml
        id: version_bump
        run: |
          # Example: Determine new version and bump logic (needs custom script or action)
          echo "New version logic goes here"
          NEW_VERSION="0.1.0"  # This should be dynamically calculated
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"
          sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" Cargo.toml

      - name: Commit and Tag New Version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml
          git commit -m "Bump version to ${{ steps.version_bump.outputs.NEW_VERSION }}"
          git tag -a "v${{ steps.version_bump.outputs.NEW_VERSION }}" -m "Release v${{ steps.version_bump.outputs.NEW_VERSION }}"
          git push origin master --tags

      - name: Output New Version
        run: "echo New Version: ${{ steps.version_bump.outputs.NEW_VERSION }} tagged and pushed"
